<TrackingScreen>:
    md_bg_color: app.theme_cls.primaryFixedColor

    MDBoxLayout:
        orientation: "vertical"

        MDLabel:
            text: "Tracking"
            halign: "center"

        MDBoxLayout:
            md_bg_color: app.theme_cls.primaryContainerColor

            id: symptom_chart
            height: "150dp"
            padding: "10dp"

            MDBoxLayout:
                orientation: "horizontal"

                MDButton:

                    MDButtonText:
                        text: "Graph"

                MDButton:

                    MDButtonText:
                        text: "Export"

        Image:
            source: "placeholder_graph.png"
            allow_stretch: True
            keep_ratio: True

        