#:import HomeScreen main.HomeScreen
#:import ProfileScreen main.ProfileScreen
#:import TrackingScreen main.TrackingScreen
#:import ResourcesScreen main.ResourcesScreen
#:import SettingsScreen main.SettingsScreen
#:import SymptomQForm main.SymptomQForm
#:import MedQForm main.MedQForm

MDBoxLayout:
    orientation: "vertical"
    md_bg_color: app.theme_cls.primaryColor
    
    MDTopAppBar:
        id: nav_bar
        type: "small"

        MDTopAppBarLeadingButtonContainer:

            MDActionTopAppBarButton:
                id: nav_button
                icon: "dots-vertical"
                on_release: app.open_nav(self)

        MDTopAppBarTitle:
            text: "Hyperflex Helper   "
            halign: "center"
    
    MDScreenManager:
        id: sm

        HomeScreen:
            name: "home"

        ProfileScreen:
            name: "profile"

        TrackingScreen:
            name: "tracking"

        ResourcesScreen:
            name: "resources"

        SettingsScreen:
            name: "settings"

        SymptomQForm:
            name: "symptomQForm"

        DrQForm:
            name: "drQForm"

        MedQForm:
            name: "medQForm"

    MDFloatLayout:
        size_hint_y: None

        MDButton:
            id: bubble
            pos_hint: {"center_x": .9, "center_y": .5}
            on_release: app.open_bubble(self)

            MDButtonIcon:
                icon: "plus" 

        