<DrQForm>:
    name: "dr_q_form"
    md_bg_color: app.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(20)
        padding: dp(20)

        MDLabel:
            text: "Add New Practitioner"
            halign: "center"

        MDTextField:
            id: symptom_input
            mode: "outlined"

            MDTextFieldHintText:
                text: "Practitioner Name Here"

            MDTextFieldHelperText:
                text: "ex: APRN M. Thompson"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDTextField:
            id: symptom_input
            mode: "outlined"

            MDTextFieldHintText:
                text: "Medical Focus"

            MDTextFieldHelperText:
                text: "ex: Primary Care Doctor"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDTextField:
            mode: "outlined"

            MDTextFieldHintText:
                text: "Next Appointment:"
            
            MDTextFieldHelperText:
                text: "ex: May 23, 2026"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDGridLayout:
            cols:  2
            spacing: "6dp"

            MDButton:
                pos_hint: {"center_x": 0.65, "bottom": 1}
                on_release: app.submit_form()

                MDButtonText:
                    text: "Submit Symptom Entry"

            MDButton:
                pos_hint: {"center_x": 0.35, "bottom": 1}
                on_release: app.change_screen("tracking")

                MDButtonText:
                    text: "Add more details"
                    