<MedQForm>:
    name: "med_q_form"
    md_bg_color: app.theme_cls.primaryFixedColor


    MDBoxLayout:
        orientation: "vertical"
        spacing: dp(20)
        padding: dp(20)

        MDLabel:
            text: "Add New Medication"
            halign: "center"

        MDTextField:
            id: symptom_input
            mode: "outlined"

            MDTextFieldHintText:
                text: "Medication Name Here"

            MDTextFieldHelperText:
                text: "ex: Cyclobenzaprine"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDTextField:
            id: symptom_input
            mode: "outlined"

            MDTextFieldHintText:
                text: "Dosage"

            MDTextFieldHelperText:
                text: "ex: 25mg nightly"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDTextField:
            mode: "outlined"

            MDTextFieldHintText:
                text: "Begin Date:"
            
            MDTextFieldHelperText:
                text: "ex: May 23, 2026"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDTextField:
            mode: "outlined"

            MDTextFieldHintText:
                text: "Notes:"
            
            MDTextFieldHelperText:
                text: "ex: take with food"
                mode: "persistent"

            MDTextFieldMaxLengthText:
                max_text_length: 50

        MDGridLayout:
            cols:  2
            spacing: "6dp"

            MDButton:
                pos_hint: {"center_x": 0.65, "bottom": 1}
                on_release: app.submit_form()

                MDButtonText:
                    text: "Submit Symptom Entry"

            MDButton:
                pos_hint: {"center_x": 0.35, "bottom": 1}
                on_release: app.change_screen("tracking")

                MDButtonText:
                    text: "Add more details"
                    